[ejs.landing]
updateAvailableTooltip = "Atualização Disponível"
usernamePlaceholder = "Nome de Usuário"
usernameEditButton = "Editar"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS DA MOJANG"
mojangStatusTooltipTitle = "Serviços"
mojangStatusNETitle = "Não&nbsp;Essencial"
newsButton = "NOTÍCIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum Servidor Selecionado"
launchDetails = "Por favor, aguarde..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando Notícias.."
newsErrorFailedSpan = "Falha ao Carregar Notícias"
newsErrorRetryButton = "Tentar Novamente"
newsErrorNoneSpan = "Sem Notícias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "LOGIN MINECRAFT"
loginEmailError = "* Valor Inválido"
loginEmailPlaceholder = "E-MAIL OU USUÁRIO"
loginPasswordError = "* Obrigatório"
loginPasswordPlaceholder = "SENHA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "esqueceu a senha?"
loginRememberMeText = "lembrar de mim?"
loginButtonText = "ENTRAR"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Precisa de uma Conta?"
loginPasswordDisclaimer1 = "Sua senha é enviada diretamente para a Mojang e nunca é armazenada."
loginPasswordDisclaimer2 = "{appName} não é afiliado à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opções de Login"
loginWithMicrosoft = "Entrar com Microsoft"
loginOffline = "Entrar Offline"
loginWithMojang = "Entrar com Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponíveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecione uma Conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Concluído"
tabAccountHeaderText = "Configurações de Conta"
tabAccountHeaderDesc = "Adicione novas contas ou gerencie as existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Adic. Conta Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Adic. Conta Mojang"
minecraftTabHeaderText = "Configurações do Minecraft"
minecraftTabHeaderDesc = "Opções relacionadas à inicialização do jogo."
gameResolutionTitle = "Resolução do Jogo"
launchFullscreenTitle = "Iniciar em tela cheia."
autoConnectTitle = "Conectar automaticamente ao servidor ao iniciar."
launchDetachedTitle = "Iniciar processo do jogo separado do launcher."
launchDetachedDesc = "Se o jogo não for separado, fechar o launcher também fechará o jogo."
tabModsHeaderText = "Configurações de Mods"
tabModsHeaderDesc = "Ativar ou desativar mods."
switchServerButton = "Trocar"
requiredMods = "Mods Obrigatórios"
optionalMods = "Mods Opcionais"
dropinMods = "Mods Drop-in (Adicionais)"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para Atualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Ativar ou desativar shaders. Note que shaders só rodam bem em computadores potentes. Você pode adicionar pacotes customizados aqui."
selectShaderpack = "Selecionar Shaderpack"
tabJavaHeaderText = "Configurações Java"
tabJavaHeaderDesc = "Gerencie a configuração do Java (avançado)."
memoryTitle = "Memória"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "A RAM mínima recomendada é de 6 gigabytes. O launcher ajusta o limite máximo conforme seu sistema (até 32 GB). Definir os valores mínimo e máximo iguais pode reduzir travamentos (lag)."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponível"
javaExecutableTitle = "Executável Java"
javaExecSelDialogTitle = "Selecionar Executável Java"
javaExecSelButtonText = "Escolher Arquivo"
javaExecDesc = "O executável Java é validado antes do lançamento do jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opções JVM Adicionais"
jvmOptsDesc = "Opções a serem fornecidas à JVM em tempo de execução. <em>-Xms</em> e <em>-Xmx</em> não devem ser incluídos."
launcherTabHeaderText = "Configurações do Launcher"
launcherTabHeaderDesc = "Opções relacionadas ao próprio launcher."
allowPrereleaseTitle = "Permitir Atualizações Pré-Lançamento."
allowPrereleaseDesc = "Pré-lançamentos incluem novos recursos que podem não ter sido totalmente testados.<br>Isso será sempre verdadeiro se você estiver usando uma versão de pré-lançamento."
dataDirectoryTitle = "Diretório de Dados"
selectDataDirectory = "Selecionar Diretório de Dados"
chooseFolder = "Escolher Pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalações locais do Java serão armazenados no diretório de dados.<br>Screenshots e saves de mundos são armazenados na pasta da instância para a configuração do servidor correspondente."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Veja informações e notas de lançamento da versão atual."
aboutTitle = "{appName}"
stableRelease = "Versão Estável"
versionText = "Versão "
sourceGithub = "Código Fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console DevTools"
releaseNotes = "Notas de Lançamento"
changelog = "Histórico de Mudanças"
noReleaseNotes = "Sem Notas de Lançamento"
viewReleaseNotes = "Ver Notas no GitHub"
launcherUpdatesHeaderText = "Atualizações do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e revise atualizações para o launcher."
checkForUpdates = "Verificar Atualizações"
whatsNew = "O que há de novo"
updateReleaseNotes = "Atualizar Notas de Lançamento"

[ejs.waiting]
waitingText = "Aguardando Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"


[js.discord]
waiting = "Aguardando Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Login Microsoft"
microsoftLogoutTitle = "Logout Microsoft"

[js.login]
login = "ENTRAR"
loggingIn = "ENTRANDO"
success = "SUCESSO"
tryAgain = "Tente Novamente"

[js.login.error]
invalidValue = "* Valor Inválido"
requiredValue = "* Obrigatório"

[js.login.error.unknown]
title = "Erro Desconhecido no Login"
desc = "Ocorreu um erro desconhecido. Por favor, verifique o console para detalhes."

[js.landing.launch]
pleaseWait = "Por favor, aguarde.."
failureTitle = "Erro ao Iniciar"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma Conta Selecionada"

[js.landing.selectedServer]
noSelection = "Nenhum Servidor Selecionado"
loading = "Carregando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.systemScan]
checking = "Verificando sistema.."
noCompatibleJava = "Nenhuma Instalação<br>Java Compatível Encontrada"
installJavaMessage = "Para iniciar o Minecraft, você precisa de uma instalação 64-bit do Java {major}. Gostaria que instalássemos uma cópia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Download do Java.."
javaDownloadFailureTitle = "Erro no Download do Java"
javaDownloadFailureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
javaRequired = "Java é Necessário<br>para Iniciar"
javaRequiredMessage = 'Uma instalação válida x64 do Java {major} é necessária.<br><br>Por favor, consulte nosso <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guia de Gerenciamento Java</a> para instruções de como instalar manualmente.'
javaRequiredDismiss = "Eu Entendo"
javaRequiredCancel = "Voltar"

[js.landing.downloadJava]
findJdkFailure = "Falha ao encontrar distribuição OpenJDK."
javaDownloadCorruptedError = "JDK baixado tem hash inválido, o arquivo pode estar corrompido."
extractingJava = "Extraindo Java"
javaInstalled = "Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Carregando informações do servidor.."
fatalError = "Erro Fatal"
unableToLoadDistributionIndex = "Não foi possível baixar o índice de distribuição. Veja o console (CTRL + Shift + i) para mais detalhes."
pleaseWait = "Por favor, aguarde.."
errorDuringLaunchTitle = "Erro Durante Lançamento"
seeConsoleForDetails = "Veja o console (CTRL + Shift + i) para mais detalhes."
validatingFileIntegrity = "Validando integridade dos arquivos.."
errorDuringFileVerificationTitle = "Erro na Verificação de Arquivos"
downloadingFiles = "Baixando arquivos.."
errorDuringFileDownloadTitle = "Erro no Download de Arquivos"
preparingToLaunch = "Preparando para iniciar.."
launchingGame = "Iniciando jogo.."
launchWrapperNotDownloaded = "O arquivo principal, LaunchWrapper, falhou ao baixar. Como resultado, o jogo não pode iniciar.<br><br>Para corrigir, desligue temporariamente seu antivírus e tente novamente.<br><br>Se tiver tempo, por favor <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">abra uma issue</a> informando seu antivírus."
doneEnjoyServer = "Pronto. Aproveite o servidor!"
checkConsoleForDetails = "Por favor, verifique o console (CTRL + Shift + i) para mais detalhes."

[js.landing.news]
checking = "Verificando Notícias"

[js.landing.discord]
loading = "Carregando jogo.."
joining = "Entrando no Servidor!!"
joined = "Explorando o Reino!"

[js.overlay]
dismiss = "Dispensar"

[js.settings.fileSelectors]
executables = "Executáveis"
allFiles = "Todos os Arquivos"

[js.settings.mstfLogin]
errorTitle = "Algo Deu Errado"
errorMessage = "Autenticação Microsoft falhou. Tente novamente."
okButton = "OK"

[js.settings.msftLogout]
errorTitle = "Algo Deu Errado"
errorMessage = "Logout Microsoft falhou. Tente novamente."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selecionar Conta"
selectedButton = "Conta Selecionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Aviso<br>Esta é sua Última Conta"
lastAccountWarningMessage = "Para usar o launcher você deve estar logado em pelo menos uma conta. Você precisará logar novamente depois.<br><br>Tem certeza que quer sair?"
confirmButton = "Tenho Certeza"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Usuário"
uuid = "UUID"
selectAccount = "Selecionar Conta"
selectedAccount = "Conta Selecionada ✓"
logout = "Sair"

[js.settings.dropinMods]
removeButton = "Remover"
deleteFailedTitle = "Falha ao Deletar<br>Mod Drop-in {fullName}"
deleteFailedMessage = "Certifique-se que o arquivo não está em uso e tente novamente."
failedToggleTitle = "Falha ao Alternar<br>Um ou Mais Mods Drop-in"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Selecionado: Java {version} ({vendor})"
invalidSelection = "Seleção Inválida"
requiresJava = "Requer Java {major} x64."
availableOptions = "Opções Disponíveis para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-lançamento"
stableReleaseTitle = "Versão Estável"
releaseNotesFailed = "Falha ao carregar notas de lançamento."

[js.settings.updates]
newReleaseTitle = "Nova Versão Disponível"
newPreReleaseTitle = "Novo Pré-lançamento Disponível"
downloadingButton = "Baixando.."
downloadingProgressButton = "Baixando... {percent}%"
downloadButton = 'Baixar do GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Feche o launcher e execute o dmg para atualizar.</span>'
latestVersionTitle = "Você está na versão mais recente"
checkForUpdatesButton = "Verificar Atualizações"
checkingForUpdatesButton = "Verificando.."
retryUpdateButton = "Tentar Novamente"

[js.settings.msftLogin]
errorTitle = "Login Microsoft Falhou"
errorMessage = "Não foi possível autenticar sua conta Microsoft. Por favor, tente novamente."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erro Fatal: Não foi possível carregar o Índice de Distribuição"
fatalErrorMessage = "Não foi possível estabelecer conexão com nossos servidores para baixar o índice de distribuição. Nenhuma cópia local estava disponível.<br><br>O índice de distribuição é essencial para fornecer as informações do servidor. O launcher não pode iniciar sem ele. Verifique sua conexão com a internet e reinicie a aplicação."
closeButton = "Fechar"

[js.uibinder.validateAccount]
failedMessageTitle = "Falha ao Atualizar Login"
failedMessage = "Não conseguimos atualizar o login para <strong>{account}</strong>. Por favor, selecione outra conta ou faça login novamente."
failedMessageSelectAnotherAccount = "Não conseguimos atualizar o login para <strong>{account}</strong>. Por favor, faça login novamente."
loginButton = "Login"
selectAnotherAccountButton = "Selecionar Outra Conta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando Atualizações..."
installNowButton = "Instalar Agora"
checkForUpdatesButton = "Verificar Atualizações"

[js.auth.microsoft.error]
noProfileTitle = "Erro no Login:<br>Perfil Não Configurado"
noProfileDesc = "Sua conta Microsoft ainda não tem um perfil de Minecraft configurado. Se você comprou o jogo recentemente ou resgatou via Xbox Game Pass, configure seu perfil em <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erro no Login:<br>Sem Conta Xbox"
noXboxAccountDesc = "Sua conta Microsoft não tem uma conta Xbox associada."
xblBannedTitle = "Erro no Login:<br>Xbox Live Indisponível"
xblBannedDesc = "Sua conta Microsoft é de um país onde a Xbox Live não está disponível ou foi banida."
under18Title = "Erro no Login:<br>Aprovação dos Pais Necessária"
under18Desc = "Contas para usuários menores de 18 anos devem ser adicionadas a uma Família por um adulto."
unknownTitle = "Erro Desconhecido no Login"
unknownDesc = "Um erro desconhecido ocorreu. Verifique o console para detalhes."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erro Interno:<br>Método Não Permitido"
methodNotAllowedDesc = "Método não permitido. Por favor, reporte este erro."
notFoundTitle = "Erro Interno:<br>Não Encontrado"
notFoundDesc = "O endpoint de autenticação não foi encontrado. Por favor, reporte este problema."
accountMigratedTitle = "Erro no Login:<br>Conta Migrada"
accountMigratedDesc = "Você tentou logar com uma conta migrada. Tente novamente usando o email da conta."
invalidCredentialsTitle = "Erro no Login:<br>Credenciais Inválidas"
invalidCredentialsDesc = "O e-mail ou senha inseridos estão incorretos. Tente novamente."
tooManyAttemptsTitle = "Erro no Login:<br>Muitas Tentativas"
tooManyAttemptsDesc = "Houve muitas tentativas de login recentes com esta conta. Tente novamente mais tarde."
invalidTokenTitle = "Erro no Login:<br>Token Inválido"
invalidTokenDesc = "O token de acesso fornecido é inválido."
tokenHasProfileTitle = "Erro no Login:<br>Token Tem Perfil"
tokenHasProfileDesc = "Token de acesso já possui um perfil atribuído."
credentialsMissingTitle = "Erro no Login:<br>Credenciais Faltando"
credentialsMissingDesc = "Usuário/senha não foram enviados ou a senha tem menos de 3 caracteres."
invalidSaltVersionTitle = "Erro no Login:<br>Versão de Salt Inválida"
invalidSaltVersionDesc = "Versão de salt inválida."
unsupportedMediaTypeTitle = "Erro Interno:<br>Tipo de Mídia Não Suportado"
unsupportedMediaTypeDesc = "Tipo de mídia não suportado. Por favor, reporte este erro."
accountGoneTitle = "Erro no Login:<br>Conta Migrada"
accountGoneDesc = "A conta foi migrada para uma conta Microsoft. Por favor, faça login com a Microsoft."
unreachableTitle = "Erro no Login:<br>Inacessível"
unreachableDesc = "Não foi possível alcançar os servidores de autenticação. Verifique se estão online e se você tem internet."
gameNotPurchasedTitle = "Erro no Login:<br>Jogo Não Comprado"
gameNotPurchasedDesc = "A conta que você está tentando usar não possui uma cópia comprada do Minecraft. Você pode comprar em <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erro Desconhecido no Login"
unknownErrorDesc = "Um erro desconhecido ocorreu. Verifique o console para detalhes."
